"""両手ランドマーク配列の共通レイアウト。

1フレームは ``[左手63要素, 右手63要素]`` の順です。各手はMediaPipe
Handsの21点を ``x, y, z`` の順に並べます。
"""

NUM_LANDMARKS_PER_HAND = 21
COORDINATES_PER_LANDMARK = 3
HAND_DIM = NUM_LANDMARKS_PER_HAND * COORDINATES_PER_LANDMARK
LANDMARK_DIM = HAND_DIM * 2

LEFT_HAND_OFFSET = 0
RIGHT_HAND_OFFSET = HAND_DIM
LEFT_HAND_SLICE = slice(LEFT_HAND_OFFSET, LEFT_HAND_OFFSET + HAND_DIM)
RIGHT_HAND_SLICE = slice(RIGHT_HAND_OFFSET, RIGHT_HAND_OFFSET + HAND_DIM)
HAND_OFFSETS = (LEFT_HAND_OFFSET, RIGHT_HAND_OFFSET)
